/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV2RestrictionSearchcard401
 */
interface FleetmanagementV2RestrictionSearchcard401 {
  fault?: Fault;
}

export class FleetmanagementV2RestrictionSearchcard401Error extends ApiError<
  FleetmanagementV2RestrictionSearchcard401
> {}
