/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV2RestrictionSearchcard500
 */
interface FleetmanagementV2RestrictionSearchcard500 {
  fault?: Fault;
}

export class FleetmanagementV2RestrictionSearchcard500Error extends ApiError<
  FleetmanagementV2RestrictionSearchcard500
> {}
