/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface AutoRenewCardResponseDataItems {
  /** CardId and PAN of the card. ;( Semicolon is used as delimiter. */
  autoRenewReferenceId?: number | null;
  /** Reference number for each individual auto renew card in the order. */
  cardIdAndPAN?: string | null;
  /** PANID of the card */
  pANID?: number | null;
}

export const autoRenewCardResponseDataItemsSchema: Schema<AutoRenewCardResponseDataItems> = object(
  {
    autoRenewReferenceId: [
      'AutoRenewReferenceId',
      optional(nullable(number())),
    ],
    cardIdAndPAN: ['CardIdAndPAN', optional(nullable(string()))],
    pANID: ['PANID', optional(nullable(number()))],
  }
);
