/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  BudleDetailsRequest,
  budleDetailsRequestSchema,
} from './budleDetailsRequest.js';

export interface BudleDetailsReq {
  filters?: BudleDetailsRequest;
}

export const budleDetailsReqSchema: Schema<BudleDetailsReq> = lazy(() =>
  object({ filters: ['Filters', optional(budleDetailsRequestSchema)] })
);
