/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface BundleCardRestrictionStatus {
  /** Card PAN. */
  pAN?: string;
}

export const bundleCardRestrictionStatusSchema: Schema<BundleCardRestrictionStatus> = object(
  { pAN: ['PAN', optional(string())] }
);
