/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CardDetailsResponseReissueSettingEnum
 */
export enum CardDetailsResponseReissueSettingEnum {
  True = 'True',
  False = 'False',
}

/**
 * Schema for CardDetailsResponseReissueSettingEnum
 */
export const  cardDetailsResponseReissueSettingEnumSchema: Schema<CardDetailsResponseReissueSettingEnum> = stringEnum(CardDetailsResponseReissueSettingEnum);
