/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for CardDetailAutoRenewEnum
 */
export enum CardDetailAutoRenewEnum {
  Enum1 = 1,
  Enum2 = 2,
  Enum3 = 3,
}

/**
 * Schema for CardDetailAutoRenewEnum
 */
export const  cardDetailAutoRenewEnumSchema: Schema<CardDetailAutoRenewEnum> = numberEnum(CardDetailAutoRenewEnum);
