/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { UpdateCard, updateCardSchema } from './updateCard';

export interface CardManagementV1CancelRequest {
  /**
   * List of CancelCardRequest entity.
   * Each card in the list will be Cancelled.
   * The details of the entity are given below.
   */
  cards: UpdateCard[];
  /**
   * Reason id for cancelling the card.<br />
   * Optional if ReasonText is passed, else mandatory<br />
   * When passed, the reason Id will be validated with the allowed reason id’s configured for the card type of the card.<br />
   * If the reason Id is not allowed, then it will be included on the error cards response.
   * Possible values:
   * 1 (Lost)
   * 2 (Stolen)
   * 3 (Card no longer required)
   */
  reasonId?: number | null;
  /**
   * Reason text for cancelling the card.<br />
   * Optional if ReasonId is passed, else mandatory<br />
   * When Reason Id is not known to the client, the reason text can be passed.<br />
   * When Reason Text is passed and the Target Status is either Block or Damaged, the text will be validated with the allowed list of values configured for the card type of the card.
   * If the text is not allowed, then it will be included on the error cards response.
   * However, if the Target status is Temporary block or Unblock then the text will be submitted
   * Possible Values:
   * 1) Lost
   * 2) Stolen
   * 3) Card no longer required
   */
  reasonText?: string | null;
}

export const cardManagementV1CancelRequestSchema: Schema<CardManagementV1CancelRequest> = object(
  {
    cards: ['Cards', array(lazy(() => updateCardSchema))],
    reasonId: ['ReasonId', optional(nullable(number()))],
    reasonText: ['ReasonText', optional(nullable(string()))],
  }
);
