/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CardDetailsResponseCardBlockSchedulesItemsAllOf0 {
  /** Effective start date of Block / Unblock */
  fromDate?: string;
  /** Effective end date of Block / Unblock */
  toDate?: string;
}

export const cardDetailsResponseCardBlockSchedulesItemsAllOf0Schema: Schema<CardDetailsResponseCardBlockSchedulesItemsAllOf0> = object(
  {
    fromDate: ['FromDate', optional(string())],
    toDate: ['ToDate', optional(string())],
  }
);
