/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { SummaryResponse, summaryResponseSchema } from './summaryResponse';

export interface CardSummaryResponse {
  /** Unique request identifier passed from end user. This identifier helps in tracing a transaction */
  requestId?: string;
  /** Unique request identifier passed from end user. This identifier helps in tracing a transaction */
  status?: string;
  data?: SummaryResponse[];
}

export const cardSummaryResponseSchema: Schema<CardSummaryResponse> = object({
  requestId: ['RequestId', optional(string())],
  status: ['Status', optional(string())],
  data: ['Data', optional(array(lazy(() => summaryResponseSchema)))],
});
