/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CardDetailsResponseRenewedCardReissueSettingEnum
 */
export enum CardDetailsResponseRenewedCardReissueSettingEnum {
  True = 'True',
  False = 'False',
}

/**
 * Schema for CardDetailsResponseRenewedCardReissueSettingEnum
 */
export const  cardDetailsResponseRenewedCardReissueSettingEnumSchema: Schema<CardDetailsResponseRenewedCardReissueSettingEnum> = stringEnum(CardDetailsResponseRenewedCardReissueSettingEnum);
