/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { SummaryRequest, summaryRequestSchema } from './summaryRequest';

export interface CardSummaryRequest {
  /**
   * Encapsulates the details of a Summary Request.
   * Summary Request fields are same as the Search Request base class and no new fields are required.
   */
  filters?: SummaryRequest;
}

export const cardSummaryRequestSchema: Schema<CardSummaryRequest> = object({
  filters: ['Filters', optional(lazy(() => summaryRequestSchema))],
});
