/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

/** Response entity object for CardBlockSchedule  list */
export interface CardBlockSchedule {
  /**
   * Effective start date of Block / Unblock<br />
   * Format: yyyyMMdd
   */
  fromDate?: string | null;
  /**
   * Effective end date of Block / Unblock<br />
   * Format: yyyyMMdd
   */
  toDate?: string | null;
}

export const cardBlockScheduleSchema: Schema<CardBlockSchedule> = object({
  fromDate: ['FromDate', optional(nullable(string()))],
  toDate: ['ToDate', optional(nullable(string()))],
});
