/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  CardDetailsRequest,
  cardDetailsRequestSchema,
} from './cardDetailsRequest.js';

export interface CardDetailsReq {
  filters?: CardDetailsRequest;
}

export const cardDetailsReqSchema: Schema<CardDetailsReq> = lazy(() =>
  object({ filters: ['Filters', optional(cardDetailsRequestSchema)] })
);
