/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for CardDetailsResponseLocalPOSLanguageIDEnum
 */
export enum CardDetailsResponseLocalPOSLanguageIDEnum {
  Enum1 = 1,
  Enum2 = 2,
  Enum3 = 3,
  Enum4 = 4,
  Enum5 = 5,
  Enum6 = 6,
  Enum7 = 7,
  Enum8 = 8,
  Enum9 = 9,
  Enum10 = 10,
  Enum11 = 11,
  Enum12 = 12,
  Enum13 = 13,
  Enum14 = 14,
  Enum15 = 15,
  Enum16 = 16,
  Enum17 = 17,
  Enum18 = 18,
  Enum19 = 19,
  Enum20 = 20,
  Enum21 = 21,
  Enum22 = 22,
  Enum23 = 23,
  Enum24 = 24,
  Enum25 = 25,
  Enum26 = 26,
  Enum27 = 27,
  Enum28 = 28,
  Enum29 = 29,
  Enum30 = 30,
  Enum31 = 31,
}

/**
 * Schema for CardDetailsResponseLocalPOSLanguageIDEnum
 */
export const  cardDetailsResponseLocalPOSLanguageIDEnumSchema: Schema<CardDetailsResponseLocalPOSLanguageIDEnum> = numberEnum(CardDetailsResponseLocalPOSLanguageIDEnum);
