/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  SubmittedMoveCard,
  submittedMoveCardSchema,
} from './submittedMoveCard.js';

export interface CardMoveRes {
  /** API Request ID */
  requestId?: string;
  /** Move-Card reference number for tracking the execution of the request. */
  mainReference?: number;
  /** API Request Overall status */
  status?: string;
  data?: SubmittedMoveCard[];
}

export const cardMoveResSchema: Schema<CardMoveRes> = object({
  requestId: ['RequestId', optional(string())],
  mainReference: ['MainReference', optional(number())],
  status: ['Status', optional(string())],
  data: ['Data', optional(array(lazy(() => submittedMoveCardSchema)))],
});
