/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface CardMoveRequestCardsItems {
  accountNumber?: string;
  accountId?: number;
  pAN?: string;
  cardId?: number;
}

export const cardMoveRequestCardsItemsSchema: Schema<CardMoveRequestCardsItems> = object(
  {
    accountNumber: ['AccountNumber', optional(string())],
    accountId: ['AccountId', optional(number())],
    pAN: ['PAN', optional(string())],
    cardId: ['CardId', optional(number())],
  }
);
