/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CardDetailsResponsePINTypeEnum
 */
export enum CardDetailsResponsePINTypeEnum {
  Card = 'Card',
  Fleet = 'Fleet',
}

/**
 * Schema for CardDetailsResponsePINTypeEnum
 */
export const cardDetailsResponsePINTypeEnumSchema: Schema<CardDetailsResponsePINTypeEnum> = stringEnum(
  CardDetailsResponsePINTypeEnum
);
