/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  CreateBundleResponseDataItems,
  createBundleResponseDataItemsSchema,
} from './createBundleResponseDataItems';
import { ErrorDetails, errorDetailsSchema } from './errorDetails';

export interface CreateBundleResponse {
  /** Request Id */
  requestId?: string;
  /** Response status */
  status?: string;
  data?: CreateBundleResponseDataItems[];
  errors?: ErrorDetails[];
}

export const createBundleResponseSchema: Schema<CreateBundleResponse> = object({
  requestId: ['RequestId', optional(string())],
  status: ['Status', optional(string())],
  data: [
    'Data',
    optional(array(lazy(() => createBundleResponseDataItemsSchema))),
  ],
  errors: ['Errors', optional(array(lazy(() => errorDetailsSchema)))],
});
