/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

/** This entity models the data that is sent in the http response body for this operation. */
export interface CreateCardResponse {
  /** Driver and VRN of the card. ;( semicolon) is used as delimiter */
  driverAndVRN?: string | null;
  /** Reference number for each individual card in the order */
  orderCardReference?: number | null;
}

export const createCardResponseSchema: Schema<CreateCardResponse> = object({
  driverAndVRN: ['DriverAndVRN', optional(nullable(string()))],
  orderCardReference: ['OrderCardReference', optional(nullable(number()))],
});
