/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface CreateCardGroupResponseErrorCardsItems {
  /** Card Id of the card. */
  cardId?: number;
  /** PAN of the card. */
  pAN?: string;
  /** Error code for validation failure. */
  errorCode?: string;
  /** Description of validation failure. */
  errorDescription?: string;
}

export const createCardGroupResponseErrorCardsItemsSchema: Schema<CreateCardGroupResponseErrorCardsItems> = object(
  {
    cardId: ['CardId', optional(number())],
    pAN: ['PAN', optional(string())],
    errorCode: ['ErrorCode', optional(string())],
    errorDescription: ['ErrorDescription', optional(string())],
  }
);
