/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  CreateCardGroupResponse,
  createCardGroupResponseSchema,
} from './createCardGroupResponse.js';

export interface CreateCardGroupRes {
  /** Unique identifier for the request. This will be played back in the response from the request. */
  requestId?: string;
  /** Status of the request */
  status?: string;
  data?: CreateCardGroupResponse[];
}

export const createCardGroupResSchema: Schema<CreateCardGroupRes> = object({
  requestId: ['RequestId', optional(string())],
  status: ['Status', optional(string())],
  data: ['Data', optional(array(lazy(() => createCardGroupResponseSchema)))],
});
