/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface DeleteBundleResponse {
  /** API Request Id */
  requestId?: string;
  /** API Response Status */
  status?: string;
}

export const deleteBundleResponseSchema: Schema<DeleteBundleResponse> = object({
  requestId: ['RequestId', optional(string())],
  status: ['Status', optional(string())],
});
