/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { ErrorStatus, errorStatusSchema } from './errorStatus';

export interface DeleteBundleResponse {
  /** API Request Id */
  requestId?: string;
  error?: ErrorStatus;
}

export const deleteBundleResponseSchema: Schema<DeleteBundleResponse> = object({
  requestId: ['RequestId', optional(string())],
  error: ['Error', optional(lazy(() => errorStatusSchema))],
});
