/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface DeleteBundleResponse {
  /** Unique identifier for the request. This will be played back in the response from the request. */
  requestId?: string;
  /** Status of the request */
  status?: string;
}

export const deleteBundleResponseSchema: Schema<DeleteBundleResponse> = object({
  requestId: ['RequestId', optional(string())],
  status: ['Status', optional(string())],
});
