/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DeliveryAddressUpdate,
  deliveryAddressUpdateSchema,
} from './deliveryAddressUpdate';

export interface DeliveryAddressUpdateRequest {
  /**
   * Collecting Company Id of the selected payer.
   * Optional if ColCoCode is passed else Mandatory.
   */
  colCoId?: number;
  /**
   * Collecting Company Code (Shell Code) of the selected payer.
   * Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia, Ukraine etc. It is optional for other countries if ColCoID is provided.
   */
  colCoCode?: number;
  /**
   * Payer Id (i.e. Customer Id of the Payment Customer) of the selected payer.
   * Optional if PayerNumber is passed else Mandatory
   */
  payerId?: number;
  /**
   * Payer Number (Ex: GB000000123) of the selected payer.
   * Optional if PayerId is passed else Mandatory
   */
  payerNumber?: string;
  /**
   * Account ID of the customer.
   * Optional if AccountNumber is passed, else mandatory.
   */
  accountId?: number;
  /**
   * Account Number of the customer.
   * Optional if AccountId is passed, else mandatory.
   * This input is a search criterion, if given.
   */
  accountNumber?: string;
  deliveryAddressUpdates?: DeliveryAddressUpdate[];
}

export const deliveryAddressUpdateRequestSchema: Schema<DeliveryAddressUpdateRequest> = object(
  {
    colCoId: ['ColCoId', optional(number())],
    colCoCode: ['ColCoCode', optional(number())],
    payerId: ['PayerId', optional(number())],
    payerNumber: ['PayerNumber', optional(string())],
    accountId: ['AccountId', optional(number())],
    accountNumber: ['AccountNumber', optional(string())],
    deliveryAddressUpdates: [
      'DeliveryAddressUpdates',
      optional(array(lazy(() => deliveryAddressUpdateSchema))),
    ],
  }
);
