/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DeliveryAddressUpdateStatusEnum
 */
export enum DeliveryAddressUpdateStatusEnum {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PARTIALSUCCESS = 'PARTIAL_SUCCESS',
}

/**
 * Schema for DeliveryAddressUpdateStatusEnum
 */
export const deliveryAddressUpdateStatusEnumSchema: Schema<DeliveryAddressUpdateStatusEnum> = stringEnum(
  DeliveryAddressUpdateStatusEnum
);
