/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  LocationRestrictionsCountryRestrictions,
  locationRestrictionsCountryRestrictionsSchema,
} from './locationRestrictionsCountryRestrictions';
import {
  LocationRestrictionsNetworkRestrictionsItems,
  locationRestrictionsNetworkRestrictionsItemsSchema,
} from './locationRestrictionsNetworkRestrictionsItems';
import {
  LocationRestrictionsPartnerSiteRestrictionsItems,
  locationRestrictionsPartnerSiteRestrictionsItemsSchema,
} from './locationRestrictionsPartnerSiteRestrictionsItems';
import {
  LocationRestrictionsShellSiteRestrictionsItems,
  locationRestrictionsShellSiteRestrictionsItemsSchema,
} from './locationRestrictionsShellSiteRestrictionsItems';

/**
 * Location restrictions to be applied on the bundle which either allows or restricts using the cards, which are under the bundle, in the specified locations.
 * Mandatory if respective action is set as “Add”.
 * Details of location restrictions are given below.
 */
export interface LocationRestrictions {
  /**
   * An entity that encapsulate the country restrictions.
   * Optional.
   */
  countryRestrictions?: LocationRestrictionsCountryRestrictions;
  /**
   * A list of NetworkRestriction entity. Each item in the list encapsulates a network restriction in a given country.
   * Optional.
   * The details of the entity are described below:
   */
  networkRestrictions?: LocationRestrictionsNetworkRestrictionsItems[];
  /**
   * A list of ShellSiteRestriction entity. Each item in the list encapsulates a site restriction of Shell network in a given country.
   * Optional.
   * The details of the entity are described below.
   */
  shellSiteRestrictions?: LocationRestrictionsShellSiteRestrictionsItems[];
  /**
   * A list of PartnerSiteRestriction entity. Each item in the list encapsulates a site restriction of a given partner network.
   * Optional.
   * The details of the entity are described below.
   */
  partnerSiteRestrictions?: LocationRestrictionsPartnerSiteRestrictionsItems[];
}

export const locationRestrictionsSchema: Schema<LocationRestrictions> = object({
  countryRestrictions: [
    'CountryRestrictions',
    optional(lazy(() => locationRestrictionsCountryRestrictionsSchema)),
  ],
  networkRestrictions: [
    'NetworkRestrictions',
    optional(
      array(lazy(() => locationRestrictionsNetworkRestrictionsItemsSchema))
    ),
  ],
  shellSiteRestrictions: [
    'ShellSiteRestrictions',
    optional(
      array(lazy(() => locationRestrictionsShellSiteRestrictionsItemsSchema))
    ),
  ],
  partnerSiteRestrictions: [
    'PartnerSiteRestrictions',
    optional(
      array(lazy(() => locationRestrictionsPartnerSiteRestrictionsItemsSchema))
    ),
  ],
});
