/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, Schema, string } from '../schema';

/**
 * An entity that encapsulate the country restrictions.
 * Optional.
 */
export interface LocationRestrictionsCountryRestrictions {
  /**
   * Boolean	Flag indicates whether the profile is inclusive or exclusive.
   * Mandatory
   * Example: False - (inclusive), i.e. the “Countries” property lists the countries where the transactions will be allowed.
   * True - (exclusive), i.e. the “Countries” property lists the countries where the transactions will be declined.
   */
  exclusive: boolean;
  /**
   * ISO 3166-1 Numeric-3 code of the country where the network restriction is applied.
   * Example: 826 for United Kingdom.
   * Mandatory
   */
  countries: string[];
}

export const locationRestrictionsCountryRestrictionsSchema: Schema<LocationRestrictionsCountryRestrictions> = object(
  {
    exclusive: ['Exclusive', boolean()],
    countries: ['Countries', array(string())],
  }
);
