/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Filters2, filters2Schema } from './filters2';

export interface OrderCardEnquiryRequest {
  filters?: Filters2;
}

export const orderCardEnquiryRequestSchema: Schema<OrderCardEnquiryRequest> = object(
  { filters: ['Filters', optional(lazy(() => filters2Schema))] }
);
