/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  CreateCardResponse,
  createCardResponseSchema,
} from './createCardResponse';

export interface OrderCardResponse {
  /** Unique request identifier passed from end user. This identifier helps in tracing a transaction */
  requestId?: string;
  /** Indicates overall status of the request. Allowed values: SUCCESS, FAILED */
  status?: string;
  data?: CreateCardResponse[];
  /** Main order reference number for tracking. */
  mainReference?: number;
}

export const orderCardResponseSchema: Schema<OrderCardResponse> = object({
  requestId: ['RequestId', optional(string())],
  status: ['Status', optional(string())],
  data: ['Data', optional(array(lazy(() => createCardResponseSchema)))],
  mainReference: ['MainReference', optional(number())],
});
