/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { CardDetail, cardDetailSchema } from './cardDetail';

/** This entity models the data that is sent in the http request body for this operation. */
export interface OrderCardRequest {
  /** List of CardOrder entity. The fields in this entity are described below. */
  cardDetails?: CardDetail[];
}

export const orderCardRequestSchema: Schema<OrderCardRequest> = object({
  cardDetails: ['CardDetails', optional(array(lazy(() => cardDetailSchema)))],
});
