/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { OrderCardEnquiry, orderCardEnquirySchema } from './orderCardEnquiry';

export interface OrderCardEnquiryResponse {
  requestId?: string;
  status?: string;
  data?: OrderCardEnquiry[];
}

export const orderCardEnquiryResponseSchema: Schema<OrderCardEnquiryResponse> = object(
  {
    requestId: ['RequestId', optional(string())],
    status: ['Status', optional(string())],
    data: ['Data', optional(array(lazy(() => orderCardEnquirySchema)))],
  }
);
