/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface ProductRestrictionCard {
  /**
   * An array of 3-digit global product codes.
   * Optional.
   * Example: [ "033", "021", "023”]
   */
  products?: string[];
  /**
   * An array of product group IDs.
   * Optional.
   * Example: [ "670246404", "40557126" ]
   */
  productGroups?: string[];
}

export const productRestrictionCardSchema: Schema<ProductRestrictionCard> = object(
  {
    products: ['Products', optional(array(string()))],
    productGroups: ['ProductGroups', optional(array(string()))],
  }
);
