/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface ProductAllOf0 {
  /**
   * The productCode returned by the Gateway API.
   * Example: 021
   */
  globalProductCode: string | null;
  /** The description returned by the Gateway API. */
  description: string | null;
}

export const productAllOf0Schema: Schema<ProductAllOf0> = object({
  globalProductCode: ['GlobalProductCode', nullable(string())],
  description: ['Description', nullable(string())],
});
