/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  PurchaseCategoryRequest,
  purchaseCategoryRequestSchema,
} from './purchaseCategoryRequest.js';

export interface PurchaseCategoryReq {
  filters?: PurchaseCategoryRequest;
}

export const purchaseCategoryReqSchema: Schema<PurchaseCategoryReq> = lazy(() =>
  object({ filters: ['Filters', optional(purchaseCategoryRequestSchema)] })
);
