/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface RestrictionCardResponseDataItems {
  /** Account Id of the customer. */
  accountId?: number | null;
  /** Account Number of the customer. */
  accountNumber?: string | null;
  /** Unique Card Id */
  cardId?: number | null;
  /** This field will have a value only when “DayTimeRestrictionStatus” is “Failed”. */
  dayTimeRestrictionDescription?: string | null;
  /** Status of the card day/time restriction submitted to API. Based on the response from API value will be set as either “Success” or “Failed”. */
  dayTimeRestrictionStatus?: string | null;
  /** This field will have a value only when “LocationRestrictionStatus” is “Failed”. */
  locationRestrictionDescription?: string | null;
  /** Card Location restriction submitted to gateway based on gateway response value set as “Success” or “Failed”. */
  locationRestrictionStatus?: string | null;
  /** Card PAN */
  pAN?: string | null;
  /** This field will have a value only when “ProductRestrictionStatus” is “Failed”. */
  productRestrictionDescription?: string | null;
  /** Status of the card product restriction submitted */
  productRestrictionStatus?: string | null;
  /** This field will have a value only when “UsageRestrictionStatus” is “Failed”. */
  usageRestrictionDescription?: string | null;
  /** Status of the card usage restriction submitted */
  usageRestrictionStatus?: string | null;
  /**
   * Error code for validation failure.
   * Example error codes:
   * 0007, 9007, 7000, 7001.
   */
  validationErrorCode?: string | null;
  /** Description of validation failure. */
  validationErrorDescription?: string | null;
}

export const restrictionCardResponseDataItemsSchema: Schema<RestrictionCardResponseDataItems> = object(
  {
    accountId: ['AccountId', optional(nullable(number()))],
    accountNumber: ['AccountNumber', optional(nullable(string()))],
    cardId: ['CardId', optional(nullable(number()))],
    dayTimeRestrictionDescription: [
      'DayTimeRestrictionDescription',
      optional(nullable(string())),
    ],
    dayTimeRestrictionStatus: [
      'DayTimeRestrictionStatus',
      optional(nullable(string())),
    ],
    locationRestrictionDescription: [
      'LocationRestrictionDescription',
      optional(nullable(string())),
    ],
    locationRestrictionStatus: [
      'LocationRestrictionStatus',
      optional(nullable(string())),
    ],
    pAN: ['PAN', optional(nullable(string()))],
    productRestrictionDescription: [
      'ProductRestrictionDescription',
      optional(nullable(string())),
    ],
    productRestrictionStatus: [
      'ProductRestrictionStatus',
      optional(nullable(string())),
    ],
    usageRestrictionDescription: [
      'UsageRestrictionDescription',
      optional(nullable(string())),
    ],
    usageRestrictionStatus: [
      'UsageRestrictionStatus',
      optional(nullable(string())),
    ],
    validationErrorCode: ['ValidationErrorCode', optional(nullable(string()))],
    validationErrorDescription: [
      'ValidationErrorDescription',
      optional(nullable(string())),
    ],
  }
);
