/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  RestrictionSearchCardRequestFilters,
  restrictionSearchCardRequestFiltersSchema,
} from './restrictionSearchCardRequestFilters';

export interface RestrictionSearchCardRequest {
  filters?: RestrictionSearchCardRequestFilters;
}

export const restrictionSearchCardRequestSchema: Schema<RestrictionSearchCardRequest> = object(
  {
    filters: [
      'Filters',
      optional(lazy(() => restrictionSearchCardRequestFiltersSchema)),
    ],
  }
);
