/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  RestrictionSearchCardResponseDataItems,
  restrictionSearchCardResponseDataItemsSchema,
} from './restrictionSearchCardResponseDataItems';

export interface RestrictionSearchCardResponse {
  /** API Request ID */
  requestId?: string;
  /** API Response Status */
  status?: string;
  data?: RestrictionSearchCardResponseDataItems[];
}

export const restrictionSearchCardResponseSchema: Schema<RestrictionSearchCardResponse> = object(
  {
    requestId: ['RequestId', optional(string())],
    status: ['Status', optional(string())],
    data: [
      'Data',
      optional(array(lazy(() => restrictionSearchCardResponseDataItemsSchema))),
    ],
  }
);
