/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DayTimeRestrictions,
  dayTimeRestrictionsSchema,
} from './dayTimeRestrictions';
import {
  LocationRestrictions,
  locationRestrictionsSchema,
} from './locationRestrictions';
import {
  ProductRestrictions,
  productRestrictionsSchema,
} from './productRestrictions';
import { UsageRestrictions, usageRestrictionsSchema } from './usageRestrictions';

export interface RestrictionCardRequestCardsItems {
  /**
   * Account Number of the customer.
   * Optional if AccountId is passed, else Mandatory.
   * This input is a search criterion, if given.
   * Example: GB000000123
   */
  accountNumber?: string;
  /**
   * Account ID of the customer.
   * Optional if AccountNumber is passed, else Mandatory.
   * This input is a search criterion, if given.
   * Example: 123456
   */
  accountId?: number;
  /**
   * Card PAN.
   * Optional if CardId is given, else mandatory.
   * Example: 7002051006629890645
   * Note:
   * •	PAN is ignored if CardId is given.
   * When PAN matches with multiple cards, the restriction will be applied on the latest issued card.
   */
  pAN?: string;
  /**
   * Unique Card Id
   * Optional if PAN is given, else mandatory.
   * Example: 275549
   */
  cardId?: number;
  /**
   * True/False.
   * If true, the usage restrictions applied on the card in Gateway will be reset to Customer Card Type level max limits, if there are no customer level overrides available then OU card type max limits. Else, the card restrictions will be updated with the usage restrictions provided in the API.
   */
  resetUsageRestrictions?: boolean;
  /**
   * True/False.
   * If true, the Day/Time restrictions applied on the card will be deleted. Else, the card restrictions will be updated with the day/time restrictions provided in the API.
   */
  resetDayTimeRestrictions?: boolean;
  /**
   * True/False.
   * If true, Default fuel/non-fuel sets configured at the purchase category level will be applied to the card. Else, the card will be applied with product restrictions provided in the API.
   */
  resetProductRestrictions?: boolean;
  /**
   * True/False.
   * If true, the location restrictions applied on the card will be deleted. Else, the card restrictions will be updated with the location restrictions provided in the API.
   */
  resetLocationRestrictions?: boolean;
  /**
   * Day/time restrictions such as weekdays and time range to be applied on the bundle.
   * Mandatory if respective action is set as “Add”.
   * The details of DayTimeRestriction entity is given below.
   */
  dayTimeRestrictions?: DayTimeRestrictions;
  /**
   * Location restrictions to be applied on the bundle which either allows or restricts using the cards, which are under the bundle, in the specified locations.
   * Mandatory if respective action is set as “Add”.
   * Details of location restrictions are given below.
   */
  locationRestrictions?: LocationRestrictions;
  productRestrictions?: ProductRestrictions;
  usageRestrictions?: UsageRestrictions;
}

export const restrictionCardRequestCardsItemsSchema: Schema<RestrictionCardRequestCardsItems> = object(
  {
    accountNumber: ['AccountNumber', optional(string())],
    accountId: ['AccountId', optional(number())],
    pAN: ['PAN', optional(string())],
    cardId: ['CardId', optional(number())],
    resetUsageRestrictions: ['ResetUsageRestrictions', optional(boolean())],
    resetDayTimeRestrictions: ['ResetDayTimeRestrictions', optional(boolean())],
    resetProductRestrictions: ['ResetProductRestrictions', optional(boolean())],
    resetLocationRestrictions: [
      'ResetLocationRestrictions',
      optional(boolean()),
    ],
    dayTimeRestrictions: [
      'DayTimeRestrictions',
      optional(lazy(() => dayTimeRestrictionsSchema)),
    ],
    locationRestrictions: [
      'LocationRestrictions',
      optional(lazy(() => locationRestrictionsSchema)),
    ],
    productRestrictions: [
      'ProductRestrictions',
      optional(lazy(() => productRestrictionsSchema)),
    ],
    usageRestrictions: [
      'UsageRestrictions',
      optional(lazy(() => usageRestrictionsSchema)),
    ],
  }
);
