/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema } from '../schema';
import {
  DayTimeRestriction,
  dayTimeRestrictionSchema,
} from './dayTimeRestriction';
import {
  LocationRestriction,
  locationRestrictionSchema,
} from './locationRestriction';
import {
  SearchProductRestriction,
  searchProductRestrictionSchema,
} from './searchProductRestriction';
import { UsageRestriction, usageRestrictionSchema } from './usageRestriction';

export interface Restriction {
  /** Details of the usage restrictions such as day/week/month value and volume restrictions applied on the card. */
  usageRestrictions?: UsageRestriction | null;
  /** Details of the day/time restrictions such as weekdays and time range in which transactions should be allowed on the card. */
  dayTimeRestrictions?: DayTimeRestriction;
  productRestrictions?: SearchProductRestriction;
  locationRestrictions?: LocationRestriction;
}

export const restrictionSchema: Schema<Restriction> = object({
  usageRestrictions: [
    'UsageRestrictions',
    optional(nullable(lazy(() => usageRestrictionSchema))),
  ],
  dayTimeRestrictions: [
    'DayTimeRestrictions',
    optional(lazy(() => dayTimeRestrictionSchema)),
  ],
  productRestrictions: [
    'ProductRestrictions',
    optional(lazy(() => searchProductRestrictionSchema)),
  ],
  locationRestrictions: [
    'LocationRestrictions',
    optional(lazy(() => locationRestrictionSchema)),
  ],
});
