/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface ScheduleCardBlockResponseDataItems {
  /** Unique Id of the card. */
  cardId?: number;
  /**
   * Effective start date & time of Block / Unblock as updated in the intermediate queue table.
   * Format: yyyyMMdd HH:mm
   * Eg: 20230512 12:30
   */
  fromDate?: string;
  /**
   * Effective end date & time of Block / Unblock as updated in the intermediate queue table.
   * Format: yyyyMMdd HH:mm
   * Eg: 20230512 14:30
   */
  toDate?: string;
  /**
   * Effective end date & time of Block / Unblock as updated in the intermediate queue table.
   * Format: yyyyMMdd HH:mm
   * Eg: 20230512 14:30
   */
  referenceId?: number;
}

export const scheduleCardBlockResponseDataItemsSchema: Schema<ScheduleCardBlockResponseDataItems> = object(
  {
    cardId: ['CardId', optional(number())],
    fromDate: ['FromDate', optional(string())],
    toDate: ['ToDate', optional(string())],
    referenceId: ['ReferenceId', optional(number())],
  }
);
