/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  DayTimeRestrictions,
  dayTimeRestrictionsSchema,
} from './dayTimeRestrictions';
import {
  LocationRestrictions,
  locationRestrictionsSchema,
} from './locationRestrictions';
import {
  SearchProductRestriction,
  searchProductRestrictionSchema,
} from './searchProductRestriction';
import { UsageRestrictions, usageRestrictionsSchema } from './usageRestrictions';

export interface SearchCardResponseRestrictions {
  /**
   * Day/time restrictions such as weekdays and time range to be applied on the bundle.
   * Mandatory if respective action is set as “Add”.
   * The details of DayTimeRestriction entity is given below.
   */
  dayTimeRestrictions?: DayTimeRestrictions;
  /**
   * Location restrictions to be applied on the bundle which either allows or restricts using the cards, which are under the bundle, in the specified locations.
   * Mandatory if respective action is set as “Add”.
   * Details of location restrictions are given below.
   */
  locationRestrictions?: LocationRestrictions;
  productRestrictions?: SearchProductRestriction;
  usageRestrictions?: UsageRestrictions;
}

export const searchCardResponseRestrictionsSchema: Schema<SearchCardResponseRestrictions> = object(
  {
    dayTimeRestrictions: [
      'DayTimeRestrictions',
      optional(lazy(() => dayTimeRestrictionsSchema)),
    ],
    locationRestrictions: [
      'LocationRestrictions',
      optional(lazy(() => locationRestrictionsSchema)),
    ],
    productRestrictions: [
      'ProductRestrictions',
      optional(lazy(() => searchProductRestrictionSchema)),
    ],
    usageRestrictions: [
      'UsageRestrictions',
      optional(lazy(() => usageRestrictionsSchema)),
    ],
  }
);
