/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { ProductGroup, productGroupSchema } from './productGroup.js';
import {
  RestrictionProduct,
  restrictionProductSchema,
} from './restrictionProduct.js';

export interface SearchProductRestriction {
  products?: RestrictionProduct[];
  productGroups?: ProductGroup[];
}

export const searchProductRestrictionSchema: Schema<SearchProductRestriction> = lazy(
  () =>
    object({
      products: ['Products', optional(array(restrictionProductSchema))],
      productGroups: ['ProductGroups', optional(array(productGroupSchema))],
    })
);
