/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  AccountVelocityLimit,
  accountVelocityLimitSchema,
} from './accountVelocityLimit';

export interface SearchAccountLimitResponseData {
  accountId?: number | null;
  /** Account Number */
  accountNumber?: string | null;
  /** 3 digit Shell global fuel product code, if already set up. */
  referenceProduct?: string | null;
  /** The restriction condition code. */
  restrictionCondition?: string | null;
  velocityLimits?: AccountVelocityLimit[];
}

export const searchAccountLimitResponseDataSchema: Schema<SearchAccountLimitResponseData> = object(
  {
    accountId: ['AccountId', optional(nullable(number()))],
    accountNumber: ['AccountNumber', optional(nullable(string()))],
    referenceProduct: ['ReferenceProduct', optional(nullable(string()))],
    restrictionCondition: [
      'RestrictionCondition',
      optional(nullable(string())),
    ],
    velocityLimits: [
      'VelocityLimits',
      optional(array(lazy(() => accountVelocityLimitSchema))),
    ],
  }
);
