/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  SearchCardRestrictionReq,
  searchCardRestrictionReqSchema,
} from './searchCardRestrictionReq.js';

export interface SearchCardRestrictionReq1 {
  filters?: SearchCardRestrictionReq;
}

export const searchCardRestrictionReq1Schema: Schema<SearchCardRestrictionReq1> = lazy(
  () =>
    object({ filters: ['Filters', optional(searchCardRestrictionReqSchema)] })
);
