/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { ProductAllOf0, productAllOf0Schema } from './productAllOf0';
import { ProductGroup, productGroupSchema } from './productGroup';

export interface SearchProductRestriction {
  products?: ProductAllOf0[];
  productGroups?: ProductGroup[];
}

export const searchProductRestrictionSchema: Schema<SearchProductRestriction> = object(
  {
    products: ['Products', optional(array(lazy(() => productAllOf0Schema)))],
    productGroups: [
      'ProductGroups',
      optional(array(lazy(() => productGroupSchema))),
    ],
  }
);
