/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface SubmittedMoveCard {
  accountId?: string;
  accountNumber?: string;
  /** Card Id of the card. */
  cardId?: string;
  /** PAN of the card */
  pAN?: string;
  /** Reference number for tracking of update status request of the specific card, */
  moveCardReference?: string;
}

export const submittedMoveCardSchema: Schema<SubmittedMoveCard> = object({
  accountId: ['AccountId', optional(string())],
  accountNumber: ['AccountNumber', optional(string())],
  cardId: ['CardId', optional(string())],
  pAN: ['PAN', optional(string())],
  moveCardReference: ['MoveCardReference', optional(string())],
});
