/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  SummaryOfBundleResponseDataItemsCardBundlesItems,
  summaryOfBundleResponseDataItemsCardBundlesItemsSchema,
} from './summaryOfBundleResponseDataItemsCardBundlesItems';

export interface SummaryOfBundleResponseDataItems {
  /**
   * Payer Id of the bundles and cards.
   * Example: 123456
   */
  payerId?: number | null;
  /**
   * Payer Number of the bundles and cards.
   * Example: GB000000123
   */
  payerNumber?: string | null;
  /**
   * Account ID of the bundle.
   * Example: 123456
   */
  accountId?: number | null;
  /**
   * Account Number of the bundle.
   * Example: GB000000123
   */
  accountNumber?: string | null;
  /** Count of cards that are not part of the bundle in a given account. */
  countOfCardsNotInBundle?: number | null;
  /** List of Card Bundles */
  cardBundles?: SummaryOfBundleResponseDataItemsCardBundlesItems[];
}

export const summaryOfBundleResponseDataItemsSchema: Schema<SummaryOfBundleResponseDataItems> = object(
  {
    payerId: ['PayerId', optional(nullable(number()))],
    payerNumber: ['PayerNumber', optional(nullable(string()))],
    accountId: ['AccountId', optional(nullable(number()))],
    accountNumber: ['AccountNumber', optional(nullable(string()))],
    countOfCardsNotInBundle: [
      'CountOfCardsNotInBundle',
      optional(nullable(number())),
    ],
    cardBundles: [
      'CardBundles',
      optional(
        array(
          lazy(() => summaryOfBundleResponseDataItemsCardBundlesItemsSchema)
        )
      ),
    ],
  }
);
