/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  SummaryofbundleResponse,
  summaryofbundleResponseSchema,
} from './summaryofbundleResponse.js';

export interface SummaryofbundleRes {
  /** Unique identifier for the request. This will be played back in the response from the request. */
  requestId?: string;
  /** Status of the request */
  status?: string;
  data?: SummaryofbundleResponse[];
}

export const summaryofbundleResSchema: Schema<SummaryofbundleRes> = object({
  requestId: ['RequestId', optional(string())],
  status: ['Status', optional(string())],
  data: ['Data', optional(array(lazy(() => summaryofbundleResponseSchema)))],
});
