/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { SummaryofBundle, summaryofBundleSchema } from './summaryofBundle';

export interface SummaryOfBundleRequest {
  filters?: SummaryofBundle;
}

export const summaryOfBundleRequestSchema: Schema<SummaryOfBundleRequest> = object(
  { filters: ['Filters', optional(lazy(() => summaryofBundleSchema))] }
);
