/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface SummaryOfBundleResponseDataItemsCardBundlesItems {
  /** Gateway assigned unique identifier for the Card Bundle. */
  bundleId?: string | null;
  /** External system allocated Card Bundle identifier for Card Bundle. */
  externalBundleId?: string | null;
  /** Card Bundle Description. */
  description?: string | null;
  /** No of Card PAN added to the card bundle. */
  totalCards?: number | null;
}

export const summaryOfBundleResponseDataItemsCardBundlesItemsSchema: Schema<SummaryOfBundleResponseDataItemsCardBundlesItems> = object(
  {
    bundleId: ['BundleId', optional(nullable(string()))],
    externalBundleId: ['ExternalBundleId', optional(nullable(string()))],
    description: ['Description', optional(nullable(string()))],
    totalCards: ['TotalCards', optional(nullable(number()))],
  }
);
