/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { ErrorStatus, errorStatusSchema } from './errorStatus.js';

export interface UpdateBundleResponse {
  requestActionStatus?: ErrorStatus;
  dayTimeRestrictionStatus?: ErrorStatus;
  locationRestrictionStatus?: ErrorStatus;
  productRestrictionStatus?: ErrorStatus;
  usageRestrictionStatus?: ErrorStatus;
}

export const updateBundleResponseSchema: Schema<UpdateBundleResponse> = object({
  requestActionStatus: [
    'RequestActionStatus',
    optional(lazy(() => errorStatusSchema)),
  ],
  dayTimeRestrictionStatus: [
    'DayTimeRestrictionStatus',
    optional(lazy(() => errorStatusSchema)),
  ],
  locationRestrictionStatus: [
    'LocationRestrictionStatus',
    optional(lazy(() => errorStatusSchema)),
  ],
  productRestrictionStatus: [
    'ProductRestrictionStatus',
    optional(lazy(() => errorStatusSchema)),
  ],
  usageRestrictionStatus: [
    'UsageRestrictionStatus',
    optional(lazy(() => errorStatusSchema)),
  ],
});
