/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface UpdateCardGroupResponseMoveCardReferencesItems {
  /**
   * Card Id of the card.
   * Example: 123
   */
  cardId?: number | null;
  /**
   * PAN of the card.
   * Example: 7002051123456789145
   */
  pAN?: string | null;
  /** Reference number for tracking of update status request of the specific card. */
  reference?: number | null;
}

export const updateCardGroupResponseMoveCardReferencesItemsSchema: Schema<UpdateCardGroupResponseMoveCardReferencesItems> = object(
  {
    cardId: ['CardId', optional(nullable(number()))],
    pAN: ['PAN', optional(nullable(string()))],
    reference: ['Reference', optional(nullable(number()))],
  }
);
