/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UrlEnum
 */
export enum UrlEnum {
  EnumApitestshellcomtest = 'api-test.shell.com/test',
  EnumApishellcom = 'api.shell.com',
}

/**
 * Schema for UrlEnum
 */
export const  urlEnumSchema: Schema<UrlEnum> = stringEnum(UrlEnum);
