/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema } from '../schema';

export interface UsageRestrictions {
  /**
   * Maximum spend value (amount) allowed per day.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  dailySpend?: number | null;
  /**
   * Maximum spend value (amount) allowed per week.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  weeklySpend?: number | null;
  /**
   * Maximum spend value (amount) allowed per month.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  monthlySpend?: number | null;
  /**
   * Maximum spend value (amount) allowed per transaction.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  perTransactionSpend?: number | null;
  /**
   * Maximum volume (quantity) allowed per day.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  dailyVolume?: number | null;
  /**
   * Maximum volume (quantity) allowed per week.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  weeklyVolume?: number | null;
  /**
   * Maximum volume (quantity) allowed per month.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  monthlyVolume?: number | null;
  /**
   * Maximum volume (quantity) allowed per transaction.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  perTransactionVolume?: number | null;
  /**
   * Maximum number of transactions allowed per day.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  dailyTransactionCount?: number | null;
  /**
   * Maximum number of transactions allowed per week.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  weeklyTransactionCount?: number | null;
  /**
   * Maximum number of transactions allowed per month.
   * Optional.
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  monthlyTransactionCount?: number | null;
  /**
   * Maximum spend value (amount) allowed per annum.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  annualSpend?: number | null;
  /**
   * Maximum spend value (amount) allowed in card’s life time.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  lifeTimeSpend?: number | null;
  /**
   * Maximum volume (quantity) allowed per annum.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  annualVolume?: number | null;
  /**
   * Maximum volume (quantity) allowed in card’s life time.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  lifeTimeVolume?: number | null;
  /**
   * Maximum number of transactions allowed per annum.
   * Optional.
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  annualTransactionCount?: number | null;
  /**
   * Maximum number of transactions allowed in card’s lifetime.
   * Optional
   * The value ‘0’ represents not set. If Values is passed as null, will be considered as inherited.
   * Valid range: 0 to 9999999999
   */
  lifeTimeTransactionCount?: number | null;
}

export const usageRestrictionsSchema: Schema<UsageRestrictions> = object({
  dailySpend: ['DailySpend', optional(nullable(number()))],
  weeklySpend: ['WeeklySpend', optional(nullable(number()))],
  monthlySpend: ['MonthlySpend', optional(nullable(number()))],
  perTransactionSpend: ['PerTransactionSpend', optional(nullable(number()))],
  dailyVolume: ['DailyVolume', optional(nullable(number()))],
  weeklyVolume: ['WeeklyVolume', optional(nullable(number()))],
  monthlyVolume: ['MonthlyVolume', optional(nullable(number()))],
  perTransactionVolume: ['PerTransactionVolume', optional(nullable(number()))],
  dailyTransactionCount: [
    'DailyTransactionCount',
    optional(nullable(number())),
  ],
  weeklyTransactionCount: [
    'WeeklyTransactionCount',
    optional(nullable(number())),
  ],
  monthlyTransactionCount: [
    'MonthlyTransactionCount',
    optional(nullable(number())),
  ],
  annualSpend: ['AnnualSpend', optional(nullable(number()))],
  lifeTimeSpend: ['LifeTimeSpend', optional(nullable(number()))],
  annualVolume: ['AnnualVolume', optional(nullable(number()))],
  lifeTimeVolume: ['LifeTimeVolume', optional(nullable(number()))],
  annualTransactionCount: [
    'AnnualTransactionCount',
    optional(nullable(number())),
  ],
  lifeTimeTransactionCount: [
    'LifeTimeTransactionCount',
    optional(nullable(number())),
  ],
});
