/**
 * Shell Card Management APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { BearerTokenManager } from './bearerTokenManager';
import { HttpClientOptions } from './clientAdapter';
import { OAuthToken } from './models/oAuthToken';
import { UrlEnum } from './models/urlEnum';

/** An interface for all configuration parameters required by the SDK. */
export interface Configuration {
  timeout: number;
  environment: Environment;
  url: UrlEnum;
  basicAuthCredentials?: {
    username: string;
    password: string;
  };
  bearerTokenCredentials?: {
    oAuthClientId: string;
    oAuthClientSecret: string;
    oAuthToken?: OAuthToken;
    oAuthTokenProvider?: (lastOAuthToken: OAuthToken | undefined,
      authManager: BearerTokenManager) => Promise<OAuthToken>;
    oAuthOnTokenUpdate?: (token: OAuthToken) => void;
  };
  httpClientOptions?: Partial<HttpClientOptions>;
  unstable_httpClientOptions?: any;
}

/** Environments available for API */
export enum Environment {
  Production = 'production',
}
